### ISSUE TITLE
GitHub Action to Publish to HostGator

### ISSUE THREAD

**Issue by bravegnu** [Chennaipy/tasks#8]

**Comment by arockiaraj1994** [comment]
@bravegnu @gnurenga I have done my personal website from github action to bluehost. 

**I have created my person webpage using mkdocs** 

I have the github actions script as well 

```yaml
name: Build GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'example-mkdocs/**'
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
 
jobs:
  build_mkdocs:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: pip install \
            mkdocs-material
      - run: mkdocs gh-deploy --config-file example-mkdocs/mkdocs.yml --force
 
  deploy_mkdocs:
    needs: build_mkdocs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
``` 



Reference: https://thomasthornton.cloud/2024/05/01/deploying-mkdocs-to-github-pages-with-github-actions/
